# Generated by Django 4.0.6 on 2022-07-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tweet_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='replies',
            new_name='reply_to',
        ),
    ]
