# Generated by Django 4.0.6 on 2022-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_tweet_image_tweetpix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
