# Generated by Django 4.0.6 on 2022-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpix',
            name='grid',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
