# Generated by Django 4.0.6 on 2022-09-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_tweetpix_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetpix',
            name='grid',
        ),
    ]
